pre-commit:
  commands:
    format:
      run: pnpm format
      stage_fixed: true
    lint:
      run: pnpm lint --fix
      stage_fixed: true
    build:
      run: pnpm build

pre-push:
  commands:
    test:
      run: pnpm test
